### ISSUE TITLE
Pipeline testing with singularity containers for snakemake rules

### ISSUE THREAD

**Issue by AngryMaciek** [zavolanlab/binding-scanner#10]
**Is your feature request related to a problem? Please describe.**
For the development time we might work in *conda* virtual environments but for the final version the *snakemake* pipeline should be executable with both `--use-conda` and `--use-singularity` flags. At some point CI needs to be testing the containerized execution as well.

**Describe the solution you'd like**
Add the call with `--use-singularity` to the CI; conda env. would have to be updated. Is it possible to use singularity on Travis at all?

**Comment by AngryMaciek** [comment]
@krish8484 - could you please start looking into this one as well?

As I wrote above, for better contenarization, in the end, we might execute the rules in `singularity` containers. this would require another bash execution script in the integration test with the described above substitution to the `snakemake` call. On top of that, each rule in the *Snakefile* will have to get an additional field - `singularity:` which points to a URL of a container @ DockerHub.
Please take a look at the *Snakefile* of our *zarp* pipeline:
https://git.scicore.unibas.ch/zavolan_group/pipelines/zarp/-/blob/dev/Snakefile

Could you please find out is it possible to use `singularity` on Travis at all? If so - we would add this second pipeline execution (i.e. calling bash execution script) to the Travis CI as well.

For now - you do not have to test `md5` checksums again, it is enough we do all the comparisons during unit-testing and integration test while running pipeline steps in `conda` envs. Just add one more pipeline run to the CI to test whether the `singularity` mechanism works fine for us.

**Comment by AngryMaciek** [comment]
There is one important note here - you have to make sure that all the software versions in `conda` envs and in `docker` containers are exactly the same. If not - executing the pipeline in virtual environments could **potentially** lead to different calculations results than running it in containers.

During your work on that issue you most probably will encounter such statement true:
Not for every combination of packages you specified in YAML recipes for `conda` envs there exist a Docker container at the DockerHub which has exactly the same versions of the software.

To minimize the work I would recoomend you to:
* First, check what is available out there and modify your YAML files. That is easier and maybe you do not "the newest pandas" at all...
* If you really cannot find anything close and you cannot make a reasonable "match" then make an issue here - feature request with specifications of what container you are asking for. Assing the issue to me and I will make a proper Docker container and upload it to DockerHub.

**Comment by krish8484** [comment]
Apologies, I am not too familiar with this technology 

> * First, check what is available out there and modify your YAML files.

I assume I have to check what is available at DockerHub. But how should I search for these python packages?

**Comment by AngryMaciek** [comment]
*snakemake* downloads **Docker** containers, don't mind the middle-step conversion to singularity. This issue is related to using proper Dockerfiles from DockerHub.
Yes, try to find such images (best from reasonable sources, not a random user) that would contain packages specified in the YAML. If you find a good candidate please try to match versions - easier to update versions in the YAML and test run.

**Comment by krish8484** [comment]
I was not able to find python packages in dockerfiles close to ours. I suggest we write new ones.

**Comment by AngryMaciek** [comment]
I am looking through all pipeline environments in the workflow, we have 5 YAML files:
* bash - I am quite sure there is a official bash account at dockerhub and the image will be there
* combine-motevo-results - there is only Python and pandas, bash will be there together with the base env, - look through `zavolab` images at dockerhub and find a default image for Python.  As I said above numerous times: **you may need to update the versions in the YAML file to create a match**. I am most certain there exist an image with Python+Pandas at the whole Dockerhub. Did you try it?
* motevo - it already has it's own image at the `zavolab` account, so this one is done
* plot_heatmap_of_MotEvo_results - yes, you might need to create your own, please follow this template and prepare a Dockerfile: https://hub.docker.com/r/zavolab/r-zavolab Later, please post the Dockerfile here and I will upload to the official `zavolab` account
* plot_sequence_logos.yml - similarly to the one above, look at this one: https://hub.docker.com/r/zavolab/python

**Comment by krish8484** [comment]
I am pasting the dockerfile contents for the script `plot_sequence_logos.py`
```
##### BASE IMAGE #####
FROM python:3.7.4

##### METADATA #####
LABEL base.image="python:3.7.4"
LABEL version="2"
LABEL software="python"
LABEL software.version="3.7.4"
LABEL software.description="Python programming language"
LABEL software.website="https://www.python.org/"
LABEL software.documentation="https://docs.python.org/3/"
LABEL software.license="https://docs.python.org/3/license.html"
LABEL software.tags="General"
LABEL maintainer="akrish136@gmail.com"
LABEL maintainer.organisation="Biozentrum, University of Basel"
LABEL maintainer.lab="Zavolan Lab"
LABEL maintainer.license="https://spdx.org/licenses/Apache-2.0"

##### VARIABLES #####
# Use variables for convenient updates/re-usability
ENV SOFTWARE_VERSION 3.7.4

##### INSTALL #####
RUN apt-get update -y \
  && pip install --upgrade pip \
  && pip install logomaker==0.8 matplotlib==3.3.0 \
  && apt-get autoremove -y && apt-get clean \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \

```

**Comment by krish8484** [comment]
Pasting the dockerfile content of the script `plot_heatmap_of_MotEvo_results.r`
```
##### BASE IMAGE #####
FROM r-base:4.0.0

##### METADATA #####
LABEL base.image="r-base:4.0.0"
LABEL version="2"
LABEL software="4.0.0"
LABEL software.version="4.0.0"
LABEL software.description="R is a system for statistical computation and graphics."
LABEL software.website="https://www.r-project.org/"
LABEL software.documentation="https://www.r-project.org/"
LABEL software.license=""
LABEL software.tags="General"
LABEL maintainer="akrish136@gmail.com"
LABEL maintainer.organisation="Biozentrum, University of Basel"
LABEL maintainer.lab="Zavolan Lab"
LABEL maintainer.license="https://spdx.org/licenses/Apache-2.0"

##### VARIABLES #####
# Use variables for convenient updates/re-usability
ENV SOFTWARE_VERSION 4.0.0


##### INSTALL #####
RUN apt-get update -y \
  && apt-get install -y curl zlib1g-dev software-properties-common libcurl4-gnutls-dev libxml2-dev libssl-dev apt-transport-https \
  && apt-get autoremove -y \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
  && Rscript -e 'install.packages(c("ggplot2", "optparse", "ggtext"))'
```

**Comment by AngryMaciek** [comment]
OK, what about `bash` and `combine-motevo-results` ?

**Comment by krish8484** [comment]
[combine-motevo-results](https://hub.docker.com/r/amancevice/pandas/tags) and [bash](https://hub.docker.com/_/bash?tab=tags).

**Comment by AngryMaciek** [comment]
Alright, Could you please check if it is possible (and how) to have [Singularity](https://singularity.lbl.gov/) installed on a Travis machine during the CI runs? We do not need to build any containers in the CI nor activate them, just have Singularity installed - Snakemake would take care of the rest.

**Comment by krish8484** [comment]
Maybe we can add some files to `.travis` to install singularity.
See https://github.com/singularityhub/travis-ci
Will this do?

**Comment by AngryMaciek** [comment]
No, I don't think we need this. This repo is related to building images whereas we just need to have `Singularity` installed.
