### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by AngryMaciek** [zavolanlab/binding-scanner#4]
**Is your feature request related to a problem? Please describe.**
For the development process we need to set up a CI for this repository.

**Describe the solution you'd like**
GitHub Actions, Travis, CircleCI (?)

**Comment by krish8484** [comment]
They all are good at their job but I would prefer Travis, just because it is simpler to write.

**Comment by AngryMaciek** [comment]
@krish8484 at our computational cluster we have our own GitLab instance and a dedicated runner hooked into it so I have only been using gitlab CI system. If you have experience with Travis it would be actually nice if you could set it up here? If so, please assign yourself to the issue and keep in mind that alongside your scripts you also need to push tests and the testing framework. This does not have to be in one pull request. Actually, it would be a better practice to separate CI setup, merging results and ploting results into three separate feature branches, sounds OK?

**Comment by krish8484** [comment]
Ok, sounds good, I will set it up

**Comment by AngryMaciek** [comment]
@krish8484 , I am sorry, I did not notice your comment and I went on with a very basic YAML file already; I realised an hour ago that I need a CI system to progress any further.  
So I added a Travis configuration with my account and a small YAML file, but please take a look at it and comment,  it is very basic and your expertese might be helpful.

**Comment by krish8484** [comment]
No problem @AngryMaciek, for now this is fine and we may keep updating it as and when we add more code(for example, python versions). Also, are we also looking to add coveralls to check code coverage?

**Comment by AngryMaciek** [comment]
OK, thanks, then I close this issue and forward you to #9 related to the code coverage.
